"""add file_hash to receipts

Revision ID: 5bc980f71e2f
Revises: 3286d30367fa
Create Date: 2026-06-01 12:55:59.963094
"""
from alembic import op
import sqlalchemy as sa


revision = '5bc980f71e2f'
down_revision = '3286d30367fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'receipts', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_column('receipts', 'file_hash')
    # ### end Alembic commands ###
